@startuml
'https://plantuml.com/class-diagram

AppCompatActivity    <|--    BaseActivity
BaseActivity         <|--    BaseCommonActivity
BaseCommonActivity   <|--    BaseLogicActivity
BaseLogicActivity    <|--    BaseTitleActivity
BaseViewModelActivity    <|--    SplashActivity
BaseViewModelActivity <|-- GuideActivity

DialogFragment    <|--    BaseDialogFragment
BaseDialogFragment   <|--    BaseViewModelDialogFragment
BaseViewModelDialogFragment <|--    TermServiceDialogFragment


BaseLogicActivity <|-- BaseViewModelActivity

Fragment   <|--   BaseFragment
BaseFragment  <|-- BaseCommonFragment
BaseCommonFragment <|-- BaseViewModelFragment


BaseViewModelFragment  <|-- GuideFragment
@enduml